server:
  port: 9462
  undertow:
    buffer-size: 1024
    direct-buffers: true
    threads:
      io: 16
      worker: 300
logging:
  level:
    root: info
    cn.binarywang.wx.miniapp: error
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm
    time-zone: GMT+8
    default-property-inclusion: ALWAYS
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/city-walk?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    username: city-walk
    password: KaTmAjEJxynhFh7S

  main:
    allow-bean-definition-overriding: true

  mvc:
    servlet:
      load-on-startup: 1
  aop:
    proxy-target-class: true
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      timeout: 5000
      lettuce:
        pool:
          max-active: 50
          max-wait: -1
          max-idle: 50
          min-idle: 0
      password: citywalkRedis
      database: 1

mybatis:
  type-aliases-package: com.yunkesoftware.www.entity
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    mapUnderscoreToCamelCase: true
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


mybatis-plus:
  global-config:
    db-config:
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
pagehelper:
  helper-dialect: mysql
  params: count=countSql


sa-token:
  # token名称 (同时也是cookie名称)
  token-name: city-walk-token
  # token 有效期（单位：秒） 默认30天，-1 代表永久有效
  timeout: 864000
  # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
  active-timeout: -1
  # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
  is-share: true
  # token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
  token-style: tik
  # 是否输出操作日志
  is-log: false
  # 配置Sa-Token单独使用的Redis连接
  alone-redis:
    # Redis数据库索引（默认为0）
    database: 1
    # Redis服务器地址
    host: 127.0.0.1
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: citywalkRedis
    # 连接超时时间（毫秒）
    timeout: 5000ms

springdoc:
  cache:
    disabled: false
  swagger-ui:
    enabled: false
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    enabled: false
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.yunkesoftware.www
  default-flat-param-object: true
knife4j:
  enable: false
  production: true
  setting:
    language: zh_cn
