spring:
  servlet:
    multipart:
      max-request-size: 50MB
      max-file-size: 50MB
  profiles:
    active: dev
logging:
  level:
    root: info
    org.springframework.web: info
    cn.binarywang.wx.miniapp: debug
wx:
  mp:
    configs:
      - appId:   # 小程序微信公众平台appId
        secret:   # 小程序微信公众平台api秘钥
        token: 
        aesKey: 
        msgDataFormat: JSON

cache:
  type: memory

upload:
  uploadType: cos
  serverUrl: 
  accessKey: 
  secretKey: 
  bucket: 
  region: 
  post: ?x-oss-process=video/snapshot,t_1,m_fast